import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import "katex/dist/katex.min.css";
import { InlineMath, BlockMath } from "react-katex";

import MathJax from "react-mathjax";
import ParticlesBackground from "@/components/ParticlesBackground";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const inlineFormula = "\\cos (2\\theta) = \\cos^2 \\theta - \\sin^2 \\theta";
  const blockFormula = `\\frac{n!}{k!(n-k)!} = \\binom{4g} \ {5\\ g/mol}`;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParticlesBackground />
      <main className={`${styles.main} ${inter.className}`}>
        <MathJax.Provider>
          <div>
            <p>
              Inline formula: <MathJax.Node inline formula={inlineFormula} />
            </p>
            <hr></hr>
            <p>Block formula:</p>
            <MathJax.Node formula={blockFormula} />
          </div>
        </MathJax.Provider>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a href="/partA" className={styles.card} rel="noopener noreferrer">
            <h2>
              Part A <span>-&gt;</span>
            </h2>
            <p>Quiz corrections</p>
          </a>

          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              Part B <span>-&gt;</span>
            </h2>
            <p>Laboratory work</p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              Part C <span>-&gt;</span>
            </h2>
            <p>Designing a final summative test</p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              Part D <span>-&gt;</span>
            </h2>
            <p>Application - Ammonia Production</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              Part E <span>-&gt;</span>
            </h2>
            <p>Cover letter</p>
          </a>
        </div>
      </main>
    </>
  );
}
